Fix Stactic Analysis Issues
projectceladon/pciutils pull request #9
Opened 2024-08-28 03:13 UTC by pillai45

Removing the line that copies the Data from and to same memory location

Tracked-On: OAM-122729

2024-08-28 06:39 UTC, lchen43 requested changes
Because the operation of dump_alloc_data, the target / source addresss should not be same. please check.

2024-08-28 08:01 UTC, pillai45 commented
struct dump_data *dd = dev->aux;

memcpy(((struct dump_data *) dev->aux)->data, dd->data, 256);

From the above two lines: 
1. Assigned, dd= dev->aux
2. copied, dev->aux->data is copied to dd->data, but both are same. So this line is redundant

2024-08-28 08:49 UTC, kwang13 approved these changes

2024-08-28 11:31 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-08-28 16:35 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-08-29 04:09 UTC, kwang13 approved these changes

2024-08-29 08:26 UTC, lchen43 commented
> struct dump_data *dd = dev->aux;
> 
> memcpy(((struct dump_data *) dev->aux)->data, dd->data, 256);
> 
> From the above two lines:
> 
> 1. Assigned, dd= dev->aux
> 2. copied, dev->aux->data is copied to dd->data, but both are same. So this line is redundant

Have you checked the function I mentioned? I didn't see you address my concern.

2024-08-29 10:47 UTC, closed without merging